index:
  #  path: /
  #  controller: App\Controller\DefaultController::index

   path: /inicio
   controller: App\Controller\HomeController::index

# animales:
#    path: /animales
#    controller: App\Controller\HomeController::animales

# Parametro Obligatorio
# animales:
#    path: /animales/{nombre}
#    controller: App\Controller\HomeController::animales

# Parametro Opcional
# animales:
#    path: /animales/{nombre}
#    controller: App\Controller\HomeController::animales
#    defaults: { nombre : "Eleazar Pérez Arencibia" }

# Parametros Opcionales
animales:
   path: /animales/{nombre}/{apellidos}
   controller: App\Controller\HomeController::animales
   defaults: { nombre : "Eleazar",
               apellidos: "Pérez Arencibia" }
   methods: [GET]
   requirements:
      #EL nombre solo tiene que contener letras
      nombre: '[a-zA-Z ]+'
      apellidos: '[a-zA-Z ]+'
      #Los apellidos solon pueden contener numeros
      # apellidos: '[0-9]+'

redirigir:
   path: /redirigir
   controller: App\Controller\HomeController::redirigir